import type { NextPage } from "next";
import Head from "next/head";
import CanvasPerspctive from "../components/CanvasPerspective";

import styles from "../styles/Main.module.scss";

const Home: NextPage = () => {
	return (
		<div className={styles.containerMain}>
			<Head>
				<title>sampleText</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<div className={styles.containerCanvas}>
					<CanvasPerspctive />
				</div>
			</main>
		</div>
	);
};

export default Home;
