import type { NextPage } from "next";
import Head from "next/head";
<<<<<<< HEAD
import CanvasPerspective from "../components/CanvasPerspective";
=======
import CanvasPerspctive from "../components/CanvasPerspective";
>>>>>>> c35b3114b78217e3974ec1318352bc2e5a99dca7

import styles from "../styles/Main.module.scss";

const Home: NextPage = () => {
	return (
		<div className={styles.containerMain}>
			<Head>
				<title>r3f template</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<div className={styles.containerCanvas}>
<<<<<<< HEAD
					<CanvasPerspective />
=======
					<CanvasPerspctive />
>>>>>>> c35b3114b78217e3974ec1318352bc2e5a99dca7
				</div>
			</main>
		</div>
	);
};

export default Home;
